# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
baseurl: "https://cakecounty.in"
# UI configs
title: "Cake County"
subtitle: "Available designs"
author:  "Cake County's"
header:
 title: "Shots"
 subtitle: "by Cake county"
footer:
 name: "Hello World! 👋'"
 bio: "I’m a software developer who writes. And 3D print. And photograph. Basically, following my curiosity and trying to find my purpose on this beautiful big blue ball. Learn more at: https://swiftlysingh.com"
social_urls:
  instagram: "https://www.instagram.com/pushpinderpalsingh_/"
  twitter: "https://twitter.com/pushpinderpal_"
